FROM node:18

RUN npm install -g npm@latest

WORKDIR /app

COPY ["package.json", "./"]

RUN npm install -g react-scripts
RUN npm install --save react-toastify
RUN npm install

COPY . .

EXPOSE 3000

CMD ["npm", "start"]
